Form validation
Vikas-jangid/todo-app pull request #2
Opened 2021-05-10 14:04 UTC by Vikas-jangid

Vuetify Form Validation Complete

2021-05-13 07:02 UTC, sunil4infobeans commented on src/App.vue
> +
@Vikas-jangid pls remove these extra new lines.

2021-05-13 07:02 UTC, sunil4infobeans commented on src/App.vue
> +
Extra new lines need to be removed.

2021-05-13 07:03 UTC, sunil4infobeans commented on src/main.js
Pls remove non required commented code

2021-05-13 07:04 UTC, sunil4infobeans commented on src/views/AddEdit.vue
> +                <v-date-picker v-model="TodoData.date" @input="menu2 = false"></v-date-picker>
:+1:

2021-05-13 07:06 UTC, sunil4infobeans commented on src/views/AddEdit.vue
> +        status: ['Completed' , 'About to Complete' , 'Pending'],
```suggestion
        status: ['Todo' , 'In Progress' , 'Done'],
```

2021-05-13 07:07 UTC, sunil4infobeans commented on src/views/AddEdit.vue
> +                   ],
Mark default stastus as "Todo", validation will not be required for this field.

2021-05-13 07:09 UTC, sunil4infobeans commented on src/views/AddEdit.vue
> +        priorities: ['High' , 'low'],
```suggestion
        priorities: ['Low', 'High', 'Very High'],
```

2021-05-13 07:09 UTC, sunil4infobeans commented on src/views/AddEdit.vue
> +                   ],
Mark default priority as "Low", validation will not be required for this field.

2021-05-13 07:10 UTC, sunil4infobeans commented on src/views/AddEdit.vue
> +         alert('status required');
Use vuetify Dialogue.

2021-05-13 07:11 UTC, sunil4infobeans commented on src/views/AddEdit.vue
> +<style></style>
Empty style statement is not required.

2021-05-13 07:12 UTC, sunil4infobeans commented on src/views/TodoList.vue
> +<style></style>
Empty style statement is not required.

2021-05-13 07:12 UTC, sunil4infobeans requested changes
Requires a few updates.

2021-05-13 07:47 UTC, Vikas-jangid commented on src/views/AddEdit.vue
> +        priorities: ['High' , 'low'],
Priorities Changed As per  recommendation

2021-05-13 07:48 UTC, Vikas-jangid commented on src/views/AddEdit.vue
> +        status: ['Completed' , 'About to Complete' , 'Pending'],
Status Options are updated

2021-05-13 07:50 UTC, Vikas-jangid commented on src/views/AddEdit.vue
> +         alert('status required');
Ok

2021-05-13 07:51 UTC, Vikas-jangid commented on src/views/TodoList.vue
> +<style></style>
ok

2021-05-14 08:10 UTC, sunil4infobeans commented
Closing this PR against https://github.com/Vikas-jangid/todo-app/pull/5

2021-05-14 08:10 UTC, closed without merging